# Generated by Django 5.2.13 on 2026-04-25 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: «Салаты», «Десерты»', max_length=80, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Используется в data-category атрибутах HTML и в URL. Существующие значения: salads, mains, desserts, drinks.', max_length=40, unique=True, verbose_name='Slug')),
                ('icon_svg', models.TextField(blank=True, help_text='Только содержимое тега &lt;svg&gt; (path, circle и т.д.). Сам тег &lt;svg&gt; добавляется шаблоном.', verbose_name='SVG-иконка (внутреннее содержимое)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Картинка категории (опционально)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше, тем выше в списке.', verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Используется в data-id атрибутах HTML. Например: salad-avocado, main-steak.', max_length=80, unique=True, verbose_name='Slug')),
                ('description', models.TextField(help_text='Короткое описание под названием блюда.', verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена (сом)')),
                ('image', models.ImageField(blank=True, help_text='Если загружено, имеет приоритет над URL.', null=True, upload_to='dishes/', verbose_name='Изображение (загружаемое)')),
                ('image_url', models.URLField(blank=True, help_text='Используется, если картинка не загружена.', max_length=500, verbose_name='URL изображения (резерв)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в категории')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно для заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menu.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
                'ordering': ['category__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ингредиент')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='menu.dish', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ['order', 'id'],
            },
        ),
    ]
