# Generated by Django 6.0.4 on 2026-04-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_seed_demo_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=80, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ky',
            field=models.CharField(blank=True, max_length=80, verbose_name='Название (KY)'),
        ),
        migrations.AddField(
            model_name='dish',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='dish',
            name='description_ky',
            field=models.TextField(blank=True, verbose_name='Описание (KY)'),
        ),
        migrations.AddField(
            model_name='dish',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='dish',
            name='name_ky',
            field=models.CharField(blank=True, max_length=120, verbose_name='Название (KY)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Ингредиент (EN)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name_ky',
            field=models.CharField(blank=True, max_length=120, verbose_name='Ингредиент (KY)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Например: «Салаты», «Десерты»', max_length=80, verbose_name='Название (RU)'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(help_text='Короткое описание под названием блюда.', verbose_name='Описание (RU)'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название (RU)'),
        ),
        migrations.AlterField(
            model_name='fine',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='Только path/circle внутри &lt;svg&gt;. Сам тег добавляет шаблон.', verbose_name='SVG-иконка (содержимое тега)'),
        ),
        migrations.AlterField(
            model_name='inforule',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='Только path/circle внутри &lt;svg&gt;. Сам тег добавляет шаблон.', verbose_name='SVG-иконка (содержимое тега)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Ингредиент (RU)'),
        ),
    ]
